#ifndef ADDPATTERNCOMMAND_H
#define ADDPATTERNCOMMAND_H

#include <string>

#include "TrackerCommand.h"

namespace CC
{
    // Appends a new empty pattern with an auto-generated id (P1, P2, ...
    // whichever positive integer is not yet used) and a matching display
    // name. The new pattern uses default barCount/stepsPerBar so it can
    // be edited immediately. Undo removes it.
    class AddPatternCommand : public TrackerCommand
    {
    public:
        AddPatternCommand();

        void Execute(TrackerProject& project) override;
        void Undo(TrackerProject& project) override;
        const char* DisplayLabel() const override { return "Add pattern"; }

    private:
        std::string insertedId;          // generated by Execute, used by Undo
    };
}

#endif // ADDPATTERNCOMMAND_H
